Models/Event.cs
using Event_Infinity.Validators;
using System;
using System.ComponentModel.DataAnnotations;

namespace Event_Infinity.Models
{
    public class Event
    {
        public virtual int EventId { get; set; }
        //[Required]
        [Display(Name = "Event Type")]
        public virtual int EventTypeId { get; set; }
        [Required]
        [Display(Name = "Event Title")]
        [StringLength(50, ErrorMessage = "Title cannot be longer than 50 characters.")]
        public virtual string EventTitle { get; set; }

        [Display(Name = "Event Description")]
        [StringLength(150, ErrorMessage = "Event description cannot be longer than 150 characters.")]
        public virtual string EventDescription { get; set; }

        [Required]
        [Display(Name = "Event Start Date")]
        [DateValidator("EventStartDate")]
        public virtual DateTime EventStartDate { get; set; }

        [Required]
        [Display(Name = "Event End Date")]
        //  [DateValidator(DateTime.Now.ToString())]
        [DateValidator("EventEndDate")]
        public virtual DateTime EventEndDate { get; set; }
        [Required]
        public virtual string EventLocation { get; set; }
        public virtual EventType EventType { get; set; }
        [Required]
        [Display(Name = "Organizer Name")]
        public virtual string OrganizerName { get; set; }
        public virtual string OrganizerContactInfo { get; set; }
        [Required]
        [Display(Name = "Max Tickets")]
        [Range(1, 300, ErrorMessage ="Please enter a number between 0 and 300")]
        public virtual int MaxTickets { get; set; }
        [Required]
        [Display(Name = "Available Tickets")]
        [Range(1, 300, ErrorMessage = "Please enter a number between 0 and 300")]
        public virtual int AvailableTickets { get; set; }


    }
}

Models/EventType.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using System;
using System.Linq;
using System.Web;

namespace Event_Infinity.Models
{
    public class EventType
    {
        public virtual int EventTypeId { get; set; }
        [Required]
        [Display(Name = "Event Type Name")]
        public virtual string Description { get; set; }

    }
}

Controllers/EventTypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Event_Infinity.Data;
using Event_Infinity.Models;

namespace Event_Infinity.Controllers
{
    public class EventTypesController : Controller
    {
        private Models.Event_InfinityDB db = new Models.Event_InfinityDB();

        // GET: EventTypes
        public ActionResult Index()
        {
            return View(db.EventTypes.ToList());
        }

        // GET: EventTypes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EventType eventType = db.EventTypes.Find(id);
            if (eventType == null)
            {
                return HttpNotFound();
            }
            return View(eventType);
        }

        // GET: EventTypes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: EventTypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EventTypeId,Description")] EventType eventType)
        {
            if (ModelState.IsValid)
            {
                db.EventTypes.Add(eventType);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(eventType);
        }

        // GET: EventTypes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EventType eventType = db.EventTypes.Find(id);
            if (eventType == null)
            {
                return HttpNotFound();
            }
            return View(eventType);
        }

        // POST: EventTypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EventTypeId,Description")] EventType eventType)
        {
            if (ModelState.IsValid)
            {
                db.Entry(eventType).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(eventType);
        }

        // GET: EventTypes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EventType eventType = db.EventTypes.Find(id);
            if (eventType == null)
            {
                return HttpNotFound();
            }
            return View(eventType);
        }

        // POST: EventTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            EventType eventType = db.EventTypes.Find(id);
            db.EventTypes.Remove(eventType);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Event_Infinity.Data;
using Event_Infinity.Models;

namespace Event_Infinity.Controllers
{
    public class EventsController : Controller
    {
        private Models.Event_InfinityDB db = new Models.Event_InfinityDB();

        // GET: Events
        public ActionResult Index()
        {
            var events = db.Events.Include(a => a.EventType);
            return View(events.ToList());
        }

        // GET: Events/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // GET: Events/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.EventTypeId = new SelectList(db.EventTypes, "EventTypeId", "Description");
            return View();
        }

        // POST: Events/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EventId,EventTypeId,EventTitle,EventDescription,EventStartDate,EventEndDate,EventLocation,OrganizerName,OrganizerContactInfo,MaxTickets,AvailableTickets")] Event @event)
        {
            if (ModelState.IsValid)
            {
                db.Events.Add(@event);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.EventTypeId = new SelectList(db.EventTypes, "EventTypeId", "Description", @event.EventTypeId);
            return View(@event);
        }

        // GET: Events/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            ViewBag.EventTypeId = new SelectList(db.EventTypes, "EventTypeId", "Description", @event.EventTypeId);
            return View(@event);
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EventId,EventTypeId,EventTitle,EventDescription,EventStartDate,EventEndDate,EventLocation,OrganizerName,OrganizerContactInfo,MaxTickets,AvailableTickets")] Event @event)
        {
            if (ModelState.IsValid)
            {
                db.Entry(@event).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EventTypeId = new SelectList(db.EventTypes, "EventTypeId", "Description", @event.EventTypeId);
            return View(@event);
        }

        // GET: Events/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // POST: Events/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Event @event = db.Events.Find(id);
            db.Events.Remove(@event);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Event_Infinity.Models;
using Event_Infinity.Data;

namespace Event_Infinity.Controllers
{
    public class OrderController : Controller
    {
        private Models.Event_InfinityDB db = new Models.Event_InfinityDB();
        // GET: Order
        [Authorize]
        public ActionResult Index()
        {
            OrderCart cart = OrderCart.GetCart(this.HttpContext);
            OrderCartViewModel vm = new OrderCartViewModel()
            {
                OrderItems = cart.GetCartItems()
            };
            return View(vm);
        }

        //GET: Order/AddToOrder
        public ActionResult AddToCart(int id)
        {
            //OrderCart cart = new OrderCart();
            OrderCart cart = OrderCart.GetCart(this.HttpContext);
            cart.AddToCart(id);
            return RedirectToAction("Index");
        }

        //POST: Order/RemoveFromCart
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            OrderCart cart = OrderCart.GetCart(this.HttpContext);
            
            Event _event = db.Carts.SingleOrDefault(c => c.RecordId == id).EventSelected;
            int newItemCount = cart.RemoveFromCart(id);
           // cart.RemoveFromCart(id);
            ShoppingCartRemoveViewModel vm = new ShoppingCartRemoveViewModel()
            {
                DeleteId = id,
                ItemCount = newItemCount,
                Message = _event.EventTitle + " has been removed from the cart"
            };

            return Json(vm);
        }
    }
}

Views/Events/Create.cshtml
@model Event_Infinity.Models.Event

@{
    ViewBag.Title = "Create";
}

<h2>Create Events</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Submit your event today!</h4>
    <button class="button" type="button" onclick="location.href='@Url.Action("Create","EventTypes")'">Create a new Event Type</button>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.EventTypeId, "Event Type", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("EventTypeId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.EventTypeId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EventTitle, "Event Title", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EventTitle, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EventTitle, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EventDescription, "Event Description", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EventDescription, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EventDescription, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EventStartDate, "Event Start Date & Time", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EventStartDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EventStartDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EventEndDate, "Event End Date & Time", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EventEndDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EventEndDate, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.EventStartTime, "Event Start Time", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventStartTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventStartTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventEndTime, "Event End Time", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventEndTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventEndTime, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.EventLocation, "Event Location", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EventLocation, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EventLocation, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.OrganizerName, "Organizer Name", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.OrganizerName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.OrganizerName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.OrganizerContactInfo, "Organizer Contact Info", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.OrganizerContactInfo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.OrganizerContactInfo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MaxTickets, "Max Tickets", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MaxTickets, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MaxTickets, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AvailableTickets, "Available Tickets", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AvailableTickets, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AvailableTickets, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Events/Delete.cshtml
@model Event_Infinity.Models.Event

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Event</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.EventType.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventType.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventStartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventStartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventEndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventEndDate)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.EventStartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventStartTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventEndTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventEndTime)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.EventLocation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventLocation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrganizerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrganizerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrganizerContactInfo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrganizerContactInfo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaxTickets)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaxTickets)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AvailableTickets)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AvailableTickets)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Events/Details.cshtml
@model Event_Infinity.Models.Event

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Event</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.EventType.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventType.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventStartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventStartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventEndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventEndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventLocation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventLocation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrganizerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrganizerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrganizerContactInfo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrganizerContactInfo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaxTickets)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaxTickets)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AvailableTickets)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AvailableTickets)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.EventId }) |
    @Html.ActionLink("Back to List", "Index")
</p>
<button>
    @Html.ActionLink("Register", "AddToCart", "Order", new { id = Model.EventId }, null)
</button>

<button>
@Html.ActionLink("Back to Browse", "Index", "Home")
    </button>

Views/Events/Edit.cshtml
@model Event_Infinity.Models.Event

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Event</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.EventId)

    <div class="form-group">
        @Html.LabelFor(model => model.EventTypeId, "Event Type", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("EventTypeId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.EventTypeId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EventTitle, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EventTitle, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EventTitle, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EventDescription, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EventDescription, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EventDescription, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EventStartDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EventStartDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EventStartDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EventEndDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EventEndDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EventEndDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        
        @Html.LabelFor(model => model.EventLocation, "Event Location", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EventLocation, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EventLocation, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.OrganizerName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.OrganizerName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.OrganizerName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.OrganizerContactInfo, "Organizer Contact Info", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.OrganizerContactInfo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.OrganizerContactInfo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MaxTickets, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MaxTickets, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MaxTickets, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AvailableTickets, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AvailableTickets, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AvailableTickets, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}